services:
  - type: web
    name: backend
    env: node
    plan: free
    buildCommand: cd backend && npm install
    startCommand: cd backend && node index.js
    envVars:
      - key: PORT
        value: 5000

  - type: web
    name: frontend
    env: node
    plan: free
    buildCommand: cd frontend && npm install && npm run build
    startCommand: cd frontend && npm run preview -- --host 0.0.0.0 --port 3000
    envVars:
      - key: PORT
        value: 3000
